### ISSUE TITLE
error with make_scs on linux

### ISSUE THREAD

**Issue by araujoms** [bodono/scs-matlab#5]
make_scs doesn't compile on Linux (Ubuntu 18.04, gcc 7.4.0, MATLAB R2016b), because gcc doesn't accept C++ style comments by default. I gave the compiler the flag -std=c99 and it worked.

**Comment by bodono** [comment]
Thanks for letting us know, I will release a fix soon.

**Comment by bodono** [comment]
Sorry for taking so long to look at this. I have a github action that compiles and tests the code on ubuntu, recent run [here](https://github.com/bodono/scs-matlab/runs/3070410079?check_suite_focus=true). It doesn't seem to have the issue you raised, is it still a problem? If so, would you mind contributing a fix since I can't reproduce the behaviour.

**Comment by araujoms** [comment]
In the meanwhile I switched to Ubuntu 20.04, which comes with gcc 9.3.0. Same problem, same solution. If I try to compile without doing anything, I get tons of errors like

> In file included from
>/home/mateus/local/scs-matlab/scs/linsys/external/qdldl/qdldl.c:1:
>/home/mateus/local/scs-matlab/scs/linsys/external/qdldl/qdldl.h:4:1: error: C++
>style comments are not allowed in ISO C90
>    4 | // Include qdldl type options
>      | ^

The fix is merely giving gcc the flag "-std=c99", with this it accepts C++ style comments.

**Comment by bodono** [comment]
I just pushed something that should fix it. Can you try now?

**Comment by araujoms** [comment]
Just tested it, indeed, it's fixed. Thanks for taking care of it.

**Comment by bodono** [comment]
Thanks for testing!
